-- auto-generated by matugen, tokyonight theme with matugen colors
local c = {
  bg        = '{{colors.background.default.hex}}',
  bg_dark   = '{{colors.surface_container_lowest.default.hex}}',
  bg_float  = '{{colors.surface_container_low.default.hex}}',
  bg_popup  = '{{colors.surface_container.default.hex}}',
  bg_high   = '{{colors.surface_container_high.default.hex}}',

  fg        = '{{colors.on_surface.default.hex}}',
  fg_dim    = '{{colors.on_surface_variant.default.hex}}',
  border    = '{{colors.outline_variant.default.hex}}',
  outline   = '{{colors.outline.default.hex}}',

  primary   = '{{colors.primary.default.hex}}',
  on_primary = '{{colors.on_primary.default.hex}}',
  primary_c = '{{colors.primary_container.default.hex}}',

  secondary   = '{{colors.secondary.default.hex}}',
  on_secondary = '{{colors.on_secondary.default.hex}}',
  secondary_c = '{{colors.secondary_container.default.hex}}',

  tertiary    = '{{colors.tertiary.default.hex}}',
  tertiary_c  = '{{colors.tertiary_container.default.hex}}',
  on_tertiary_c = '{{colors.on_tertiary_container.default.hex}}',

  error     = '{{colors.error.default.hex}}',
  on_error  = '{{colors.on_error.default.hex}}',
  error_c   = '{{colors.error_container.default.hex}}',

  inverse   = '{{colors.inverse_surface.default.hex}}',
  inv_on    = '{{colors.inverse_on_surface.default.hex}}',
  inv_primary = '{{colors.inverse_primary.default.hex}}',
}

vim.g.matugen_colors = {
  bg        = c.bg,
  bg_dark   = c.bg_dark,
  fg        = c.fg,
  border    = c.border,
  primary   = c.primary,
  secondary = c.secondary,
  tertiary  = c.tertiary,
  error     = c.error,
}

local hl = vim.api.nvim_set_hl

-- base ui
hl(0, "Normal",        { fg = c.fg,      bg = c.bg })
hl(0, "NormalNC",      { fg = c.fg_dim,  bg = c.bg_dark })
hl(0, "NormalFloat",   { fg = c.fg,      bg = c.bg_float })
hl(0, "FloatBorder",   { fg = c.border,  bg = c.bg_float })
hl(0, "FloatTitle",    { fg = c.on_primary, bg = c.primary, bold = true })
hl(0, "Pmenu",         { fg = c.fg,      bg = c.bg_popup })
hl(0, "PmenuSel",      { fg = c.on_primary, bg = c.primary })
hl(0, "PmenuSbar",     { bg = c.bg_high })
hl(0, "PmenuThumb",    { bg = c.primary })
hl(0, "WinSeparator",  { fg = c.border,  bg = c.bg })
hl(0, "VertSplit",     { fg = c.border })
hl(0, "StatusLine",    { fg = c.fg,      bg = c.bg_dark })
hl(0, "StatusLineNC",  { fg = c.fg_dim,  bg = c.bg_dark })
hl(0, "TabLine",       { fg = c.fg_dim,  bg = c.bg_dark })
hl(0, "TabLineFill",   { bg = c.bg_dark })
hl(0, "TabLineSel",    { fg = c.on_primary, bg = c.primary })
hl(0, "LineNr",        { fg = c.border })
hl(0, "CursorLineNr",  { fg = c.primary, bold = true })
hl(0, "CursorLine",    { bg = c.bg_float })
hl(0, "CursorColumn",  { bg = c.bg_float })
hl(0, "ColorColumn",   { bg = c.bg_float })
hl(0, "SignColumn",    { fg = c.fg_dim,  bg = c.bg })
hl(0, "EndOfBuffer",   { fg = c.border })
hl(0, "Folded",        { fg = c.fg_dim,  bg = c.bg_float })
hl(0, "FoldColumn",    { fg = c.border,  bg = c.bg })
hl(0, "Visual",        { bg = c.primary_c })
hl(0, "VisualNOS",     { bg = c.primary_c })
hl(0, "IncSearch",     { fg = c.on_secondary, bg = c.secondary })
hl(0, "Search",        { fg = c.on_primary,   bg = c.primary })
hl(0, "CurSearch",     { fg = c.on_primary,   bg = c.primary })
hl(0, "MatchParen",    { fg = c.tertiary,  bold = true, underline = true })
hl(0, "Substitute",    { fg = c.on_secondary, bg = c.secondary })
hl(0, "MsgArea",       { fg = c.fg,       bg = c.bg_dark })
hl(0, "MsgSeparator",  { fg = c.border })
hl(0, "MoreMsg",       { fg = c.primary })
hl(0, "Question",      { fg = c.primary })
hl(0, "ErrorMsg",      { fg = c.error })
hl(0, "WarningMsg",    { fg = c.secondary })
hl(0, "Title",         { fg = c.primary,  bold = true })
hl(0, "Directory",     { fg = c.primary })
hl(0, "SpecialKey",    { fg = c.tertiary })
hl(0, "NonText",       { fg = c.border })
hl(0, "Whitespace",    { fg = c.border })
hl(0, "Conceal",       { fg = c.fg_dim })
hl(0, "WildMenu",      { fg = c.on_primary, bg = c.primary })
hl(0, "qfLineNr",      { fg = c.primary })
hl(0, "qfFileName",    { fg = c.secondary })

-- syntax
hl(0, "Comment",       { fg = c.on_tertiary_c, italic = true })
hl(0, "Constant",      { fg = c.secondary })
hl(0, "String",        { fg = c.tertiary })
hl(0, "Character",     { fg = c.tertiary })
hl(0, "Number",        { fg = c.secondary })
hl(0, "Boolean",       { fg = c.secondary })
hl(0, "Float",         { fg = c.secondary })
hl(0, "Identifier",    { fg = c.fg })
hl(0, "Function",      { fg = c.primary })
hl(0, "Statement",     { fg = c.secondary })
hl(0, "Conditional",   { fg = c.secondary })
hl(0, "Repeat",        { fg = c.secondary })
hl(0, "Label",         { fg = c.secondary })
hl(0, "Operator",      { fg = c.fg_dim })
hl(0, "Keyword",       { fg = c.secondary })
hl(0, "Exception",     { fg = c.error })
hl(0, "PreProc",       { fg = c.tertiary })
hl(0, "Include",       { fg = c.tertiary })
hl(0, "Define",        { fg = c.tertiary })
hl(0, "Macro",         { fg = c.tertiary })
hl(0, "PreCondit",     { fg = c.tertiary })
hl(0, "Type",          { fg = c.primary })
hl(0, "StorageClass",  { fg = c.secondary })
hl(0, "Structure",     { fg = c.primary })
hl(0, "Typedef",       { fg = c.primary })
hl(0, "Special",       { fg = c.tertiary })
hl(0, "SpecialChar",   { fg = c.tertiary })
hl(0, "Tag",           { fg = c.primary })
hl(0, "Delimiter",     { fg = c.fg_dim })
hl(0, "SpecialComment",{ fg = c.on_tertiary_c, italic = true })
hl(0, "Debug",         { fg = c.error })
hl(0, "Underlined",    { underline = true })
hl(0, "Error",         { fg = c.error })
hl(0, "Todo",          { fg = c.on_secondary, bg = c.secondary_c, bold = true })

-- treesitter (nvim 0.8+ @-prefixed groups)
hl(0, "@comment",                { fg = c.on_tertiary_c, italic = true })
hl(0, "@comment.documentation",  { fg = c.fg_dim, italic = true })
hl(0, "@string",                 { fg = c.tertiary })
hl(0, "@string.regex",           { fg = c.secondary })
hl(0, "@string.escape",          { fg = c.secondary })
hl(0, "@string.special",         { fg = c.secondary })
hl(0, "@character",              { fg = c.tertiary })
hl(0, "@number",                 { fg = c.secondary })
hl(0, "@boolean",                { fg = c.secondary })
hl(0, "@float",                  { fg = c.secondary })
hl(0, "@function",               { fg = c.primary })
hl(0, "@function.builtin",       { fg = c.tertiary })
hl(0, "@function.call",          { fg = c.primary })
hl(0, "@function.macro",         { fg = c.tertiary })
hl(0, "@function.method",        { fg = c.primary })
hl(0, "@function.method.call",   { fg = c.primary })
hl(0, "@parameter",              { fg = c.fg })
hl(0, "@constructor",            { fg = c.primary })
hl(0, "@conditional",            { fg = c.secondary })
hl(0, "@conditional.ternary",    { fg = c.secondary })
hl(0, "@repeat",                 { fg = c.secondary })
hl(0, "@label",                  { fg = c.secondary })
hl(0, "@operator",               { fg = c.fg_dim })
hl(0, "@keyword",                { fg = c.secondary })
hl(0, "@keyword.function",       { fg = c.secondary })
hl(0, "@keyword.operator",       { fg = c.secondary })
hl(0, "@keyword.return",         { fg = c.secondary })
hl(0, "@keyword.import",         { fg = c.tertiary })
hl(0, "@keyword.modifier",       { fg = c.secondary })
hl(0, "@keyword.repeat",         { fg = c.secondary })
hl(0, "@keyword.conditional",    { fg = c.secondary })
hl(0, "@exception",              { fg = c.error })
hl(0, "@type",                   { fg = c.primary })
hl(0, "@type.builtin",           { fg = c.primary })
hl(0, "@type.definition",        { fg = c.primary })
hl(0, "@type.qualifier",         { fg = c.secondary })
hl(0, "@storageclass",           { fg = c.secondary })
hl(0, "@attribute",              { fg = c.tertiary })
hl(0, "@namespace",              { fg = c.fg })
hl(0, "@module",                 { fg = c.fg })
hl(0, "@include",                { fg = c.tertiary })
hl(0, "@preproc",                { fg = c.tertiary })
hl(0, "@variable",               { fg = c.fg })
hl(0, "@variable.builtin",       { fg = c.secondary })
hl(0, "@variable.parameter",     { fg = c.fg })
hl(0, "@variable.member",        { fg = c.fg })
hl(0, "@field",                  { fg = c.fg })
hl(0, "@property",               { fg = c.fg })
hl(0, "@punctuation",            { fg = c.fg_dim })
hl(0, "@punctuation.bracket",    { fg = c.fg_dim })
hl(0, "@punctuation.delimiter",  { fg = c.fg_dim })
hl(0, "@punctuation.special",    { fg = c.tertiary })
hl(0, "@tag",                    { fg = c.primary })
hl(0, "@tag.attribute",          { fg = c.secondary })
hl(0, "@tag.delimiter",          { fg = c.fg_dim })
hl(0, "@text",                   { fg = c.fg })
hl(0, "@text.title",             { fg = c.primary, bold = true })
hl(0, "@text.emphasis",          { italic = true })
hl(0, "@text.strong",            { bold = true })
hl(0, "@text.strike",            { strikethrough = true })
hl(0, "@text.literal",           { fg = c.tertiary })
hl(0, "@text.uri",               { fg = c.tertiary, underline = true })
hl(0, "@text.reference",         { fg = c.primary })
hl(0, "@text.todo",              { fg = c.on_secondary, bg = c.secondary_c, bold = true })
hl(0, "@text.warning",           { fg = c.bg, bg = c.secondary })
hl(0, "@text.danger",            { fg = c.bg, bg = c.error })
hl(0, "@text.diff.add",          { fg = c.primary })
hl(0, "@text.diff.delete",       { fg = c.error })

-- diagnostics
hl(0, "DiagnosticError",              { fg = c.error })
hl(0, "DiagnosticWarn",               { fg = c.secondary })
hl(0, "DiagnosticInfo",               { fg = c.primary })
hl(0, "DiagnosticHint",               { fg = c.tertiary })
hl(0, "DiagnosticVirtualTextError",   { fg = c.error,     bg = c.bg_dark })
hl(0, "DiagnosticVirtualTextWarn",    { fg = c.secondary, bg = c.bg_dark })
hl(0, "DiagnosticVirtualTextInfo",    { fg = c.primary,   bg = c.bg_dark })
hl(0, "DiagnosticVirtualTextHint",    { fg = c.tertiary,  bg = c.bg_dark })
hl(0, "DiagnosticUnderlineError",     { undercurl = true, sp = c.error })
hl(0, "DiagnosticUnderlineWarn",      { undercurl = true, sp = c.secondary })
hl(0, "DiagnosticUnderlineInfo",      { undercurl = true, sp = c.primary })
hl(0, "DiagnosticUnderlineHint",      { undercurl = true, sp = c.tertiary })
hl(0, "DiagnosticSignError",          { fg = c.error })
hl(0, "DiagnosticSignWarn",           { fg = c.secondary })
hl(0, "DiagnosticSignInfo",           { fg = c.primary })
hl(0, "DiagnosticSignHint",           { fg = c.tertiary })

-- lsp
hl(0, "LspReferenceText",             { bg = c.bg_high })
hl(0, "LspReferenceRead",             { bg = c.bg_high })
hl(0, "LspReferenceWrite",            { bg = c.bg_high })
hl(0, "LspInlayHint",                 { fg = c.border, bg = c.bg_dark, italic = true })

-- git signs
hl(0, "GitSignsAdd",                  { fg = c.primary })
hl(0, "GitSignsChange",               { fg = c.secondary })
hl(0, "GitSignsDelete",               { fg = c.error })
hl(0, "GitSignsAddNr",                { fg = c.primary })
hl(0, "GitSignsChangeNr",             { fg = c.secondary })
hl(0, "GitSignsDeleteNr",             { fg = c.error })

-- telescope
hl(0, "TelescopeNormal",              { fg = c.fg,     bg = c.bg_float })
hl(0, "TelescopeBorder",              { fg = c.border, bg = c.bg_float })
hl(0, "TelescopePromptNormal",        { fg = c.fg,     bg = c.bg_popup })
hl(0, "TelescopePromptBorder",        { fg = c.border, bg = c.bg_popup })
hl(0, "TelescopePromptTitle",         { fg = c.on_primary,   bg = c.primary,   bold = true })
hl(0, "TelescopePreviewTitle",        { fg = c.on_secondary, bg = c.secondary, bold = true })
hl(0, "TelescopeResultsTitle",        { fg = c.on_primary,   bg = c.primary_c, bold = true })
hl(0, "TelescopeSelection",           { bg = c.primary_c })
hl(0, "TelescopeSelectionCaret",      { fg = c.primary, bg = c.primary_c })
hl(0, "TelescopeMatching",            { fg = c.primary, bold = true })
hl(0, "TelescopePromptPrefix",        { fg = c.primary, bg = c.bg_popup })

-- neo-tree
hl(0, "NeoTreeNormal",                { fg = c.fg,     bg = c.bg_dark })
hl(0, "NeoTreeNormalNC",              { fg = c.fg,     bg = c.bg_dark })
hl(0, "NeoTreeWinSeparator",          { fg = c.border, bg = c.bg })
hl(0, "NeoTreeEndOfBuffer",           { fg = c.bg_dark, bg = c.bg_dark })
hl(0, "NeoTreeRootName",              { fg = c.primary, bold = true })
hl(0, "NeoTreeGitAdded",              { fg = c.primary })
hl(0, "NeoTreeGitModified",           { fg = c.secondary })
hl(0, "NeoTreeGitDeleted",            { fg = c.error })
hl(0, "NeoTreeGitConflict",           { fg = c.error, bold = true })
hl(0, "NeoTreeGitUntracked",          { fg = c.fg_dim })
hl(0, "NeoTreeGitIgnored",            { fg = c.border })
hl(0, "NeoTreeDirectoryName",         { fg = c.primary })
hl(0, "NeoTreeDirectoryIcon",         { fg = c.primary })
hl(0, "NeoTreeFileName",              { fg = c.fg })
hl(0, "NeoTreeFileNameOpened",        { fg = c.secondary })
hl(0, "NeoTreeIndentMarker",          { fg = c.border })
hl(0, "NeoTreeExpander",              { fg = c.primary })
hl(0, "NeoTreeTitleBar",              { fg = c.on_primary, bg = c.primary })
hl(0, "NeoTreeFloatBorder",           { fg = c.border, bg = c.bg_float })

-- bufferline
hl(0, "BufferLineBackground",          { fg = c.fg_dim,     bg = c.bg_dark })
hl(0, "BufferLineBufferSelected",      { fg = c.fg,         bg = c.bg,     bold = true })
hl(0, "BufferLineBufferVisible",       { fg = c.fg_dim,     bg = c.bg_dark })
hl(0, "BufferLineFill",                { bg = c.bg_dark })
hl(0, "BufferLineSeparator",           { fg = c.bg_dark,    bg = c.bg_dark })
hl(0, "BufferLineSeparatorSelected",   { fg = c.bg_dark,    bg = c.bg })
hl(0, "BufferLineSeparatorVisible",    { fg = c.bg_dark,    bg = c.bg_dark })
hl(0, "BufferLineIndicatorSelected",   { fg = c.primary,    bg = c.bg })
hl(0, "BufferLineIndicatorVisible",    { fg = c.border,     bg = c.bg_dark })
hl(0, "BufferLineTab",                 { fg = c.fg_dim,     bg = c.bg_dark })
hl(0, "BufferLineTabSelected",         { fg = c.primary,    bg = c.bg,     bold = true })
hl(0, "BufferLineTabSeparator",        { fg = c.bg_dark,    bg = c.bg_dark })
hl(0, "BufferLineTabSeparatorSelected",{ fg = c.bg_dark,    bg = c.bg })
hl(0, "BufferLineModified",            { fg = c.secondary,  bg = c.bg_dark })
hl(0, "BufferLineModifiedSelected",    { fg = c.secondary,  bg = c.bg })
hl(0, "BufferLineModifiedVisible",     { fg = c.secondary,  bg = c.bg_dark })
hl(0, "BufferLineDiagnostic",          { fg = c.fg_dim,     bg = c.bg_dark })
hl(0, "BufferLineDiagnosticSelected",  { fg = c.fg,         bg = c.bg })
hl(0, "BufferLineError",               { fg = c.error,      bg = c.bg_dark })
hl(0, "BufferLineErrorSelected",       { fg = c.error,      bg = c.bg,     bold = true })
hl(0, "BufferLineWarning",             { fg = c.secondary,  bg = c.bg_dark })
hl(0, "BufferLineWarningSelected",     { fg = c.secondary,  bg = c.bg,     bold = true })
hl(0, "BufferLineHint",                { fg = c.tertiary,   bg = c.bg_dark })
hl(0, "BufferLineHintSelected",        { fg = c.tertiary,   bg = c.bg,     bold = true })
hl(0, "BufferLineCloseButton",         { fg = c.fg_dim,     bg = c.bg_dark })
hl(0, "BufferLineCloseButtonSelected", { fg = c.error,      bg = c.bg })
hl(0, "BufferLineOffset",              { fg = c.fg_dim,     bg = c.bg_dark })
hl(0, "BufferLineOffsetSeparator",     { fg = c.border,     bg = c.bg_dark })
hl(0, "BufferLineNumbers",             { fg = c.border,     bg = c.bg_dark })
hl(0, "BufferLineNumbersSelected",     { fg = c.primary,    bg = c.bg })

-- indent-blankline
hl(0, "IblIndent",                     { fg = c.border })
hl(0, "IblScope",                      { fg = c.primary })
hl(0, "IblWhitespace",                 { fg = c.border })

-- which-key
hl(0, "WhichKey",                      { fg = c.primary })
hl(0, "WhichKeyGroup",                 { fg = c.secondary })
hl(0, "WhichKeyDesc",                  { fg = c.fg })
hl(0, "WhichKeySeparator",             { fg = c.border })
hl(0, "WhichKeyValue",                 { fg = c.fg_dim })
hl(0, "WhichKeyBorder",                { fg = c.border })
hl(0, "WhichKeyNormal",                { bg = c.bg_float })

-- nvim-cmp completion menu
hl(0, "CmpNormal",                     { bg = c.bg_popup })
hl(0, "CmpBorder",                     { fg = c.border })
hl(0, "CmpDocBorder",                  { fg = c.border })
hl(0, "CmpDoc",                        { bg = c.bg_float })
hl(0, "CmpItemAbbr",                   { fg = c.fg })
hl(0, "CmpItemAbbrDeprecated",         { fg = c.fg_dim, strikethrough = true })
hl(0, "CmpItemAbbrMatch",              { fg = c.primary, bold = true })
hl(0, "CmpItemAbbrMatchFuzzy",         { fg = c.primary })
hl(0, "CmpItemKind",                   { fg = c.secondary })
hl(0, "CmpItemMenu",                   { fg = c.fg_dim })
hl(0, "CmpItemKindClass",              { fg = c.primary })
hl(0, "CmpItemKindFunction",           { fg = c.primary })
hl(0, "CmpItemKindMethod",             { fg = c.primary })
hl(0, "CmpItemKindKeyword",            { fg = c.secondary })
hl(0, "CmpItemKindVariable",           { fg = c.fg })
hl(0, "CmpItemKindSnippet",            { fg = c.tertiary })
hl(0, "CmpItemKindModule",             { fg = c.tertiary })
hl(0, "CmpItemKindText",               { fg = c.fg_dim })

-- toggleterm
hl(0, "ToggleTerm1FloatBorder",        { fg = c.border })
hl(0, "ToggleTerm1NormalFloat",        { bg = c.bg_float })

-- scrollbar
hl(0, "ScrollbarHandle",               { bg = c.bg_high })
hl(0, "ScrollbarCursorHandle",         { bg = c.primary })
hl(0, "ScrollbarCursor",               { fg = c.primary })
hl(0, "ScrollbarError",                { fg = c.error })
hl(0, "ScrollbarErrorHandle",          { fg = c.error, bg = c.bg_high })
hl(0, "ScrollbarWarn",                 { fg = c.secondary })
hl(0, "ScrollbarWarnHandle",           { fg = c.secondary, bg = c.bg_high })
hl(0, "ScrollbarInfo",                 { fg = c.primary })
hl(0, "ScrollbarInfoHandle",           { fg = c.primary, bg = c.bg_high })
hl(0, "ScrollbarHint",                 { fg = c.tertiary })
hl(0, "ScrollbarHintHandle",           { fg = c.tertiary, bg = c.bg_high })
hl(0, "ScrollbarGitAdd",               { fg = c.primary })
hl(0, "ScrollbarGitAddHandle",         { fg = c.primary, bg = c.bg_high })
hl(0, "ScrollbarGitChange",            { fg = c.secondary })
hl(0, "ScrollbarGitChangeHandle",      { fg = c.secondary, bg = c.bg_high })
hl(0, "ScrollbarGitDelete",            { fg = c.error })
hl(0, "ScrollbarGitDeleteHandle",      { fg = c.error, bg = c.bg_high })

-- mason
hl(0, "MasonNormal",                   { bg = c.bg_float })
hl(0, "MasonHeader",                   { fg = c.on_primary, bg = c.primary, bold = true })
hl(0, "MasonHeaderSecondary",          { fg = c.on_secondary, bg = c.secondary, bold = true })
hl(0, "MasonHighlight",                { fg = c.primary })
hl(0, "MasonHighlightSecondary",       { fg = c.secondary })
hl(0, "MasonHighlightBlock",           { fg = c.on_primary,   bg = c.primary })
hl(0, "MasonHighlightBlockBold",       { fg = c.on_primary,   bg = c.primary, bold = true })
hl(0, "MasonHighlightBlockSecondary",  { fg = c.on_secondary, bg = c.secondary })
hl(0, "MasonMuted",                    { fg = c.fg_dim })
hl(0, "MasonMutedBlock",               { fg = c.fg_dim, bg = c.bg_popup })
hl(0, "MasonLink",                     { fg = c.tertiary, underline = true })

-- lazy.nvim
hl(0, "LazyNormal",                    { bg = c.bg_float })
hl(0, "LazyBorder",                    { fg = c.border, bg = c.bg_float })
hl(0, "LazyButton",                    { fg = c.fg,     bg = c.bg_high })
hl(0, "LazyButtonActive",              { fg = c.on_primary, bg = c.primary, bold = true })
hl(0, "LazyH1",                        { fg = c.on_primary, bg = c.primary, bold = true })
hl(0, "LazyH2",                        { fg = c.primary, bold = true })
hl(0, "LazyDimmed",                    { fg = c.fg_dim })
hl(0, "LazyProgressDone",              { fg = c.primary })
hl(0, "LazyProgressTodo",              { fg = c.border })
hl(0, "LazyProp",                      { fg = c.secondary })
hl(0, "LazyReasonPlugin",              { fg = c.primary })
hl(0, "LazyReasonCmd",                 { fg = c.secondary })
hl(0, "LazyReasonEvent",               { fg = c.tertiary })
hl(0, "LazyReasonSource",              { fg = c.tertiary })

-- rebuild lualine theme with new palette
vim.schedule(function()
  if _G._matugen_rebuild_lualine then
    _G._matugen_rebuild_lualine()
  end
end)
