#!/usr/bin/env bash
# disable display manager, configure TTY1 autologin via systemd getty

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

# dm list
readonly KNOWN_DMS=(
    "sddm"
    "gdm"
    "lightdm"
    "ly"
    "greetd"
    "lxdm"
    "slim"
    "xdm"
    "mdm"
    "entrance"
)

# detect dm
detect_display_managers() {
    local service
    for service in "${KNOWN_DMS[@]}"; do
        if systemctl is-enabled "${service}.service" &>/dev/null || \
           systemctl is-active  "${service}.service" &>/dev/null; then
            echo "$service"
        fi
    done
}

# disable and mask dm service
disable_display_manager() {
    local service="$1"

    log_substep "Disabling ${service}.service ..."
    sudo systemctl disable "${service}.service" 2>/dev/null \
        || log_warn "  Could not disable ${service}.service (may already be disabled)"

    log_substep "Masking ${service}.service ..."
    sudo systemctl mask "${service}.service" 2>/dev/null \
        || log_warn "  Could not mask ${service}.service"

    log_info "  ${YELLOW}(not stopped - takes effect after reboot)${RESET}"
}

# config tty1 autologin
configure_tty1_autologin() {
    local username="${USER:-$(id -un)}"
    local override_dir="/etc/systemd/system/getty@tty1.service.d"
    local override_file="${override_dir}/autologin.conf"

    # detect agetty binary path
    local agetty_bin
    agetty_bin="$(command -v agetty 2>/dev/null || echo "/sbin/agetty")"

    log_substep "Writing TTY1 autologin override for user '${username}' ..."

    sudo mkdir -p "$override_dir"

    sudo tee "$override_file" > /dev/null << EOF
# generated by 09_autologin.sh
# user: ${username}
[Service]
ExecStart=
ExecStart=-${agetty_bin} -o '-p -f -- \\u' --noclear --noissue --autologin ${username} %I \$TERM
EOF

    sudo systemctl daemon-reload
    log_success "TTY1 autologin configured → /etc/systemd/system/getty@tty1.service.d/autologin.conf"
}

# main
main() {
    log_step "Autologin Setup"

    # fetch dm
    local found_dms=()
    local dm
    while IFS= read -r dm; do
        [[ -n "$dm" ]] && found_dms+=("$dm")
    done < <(detect_display_managers)

    # already config
    if [[ ${#found_dms[@]} -eq 0 ]] && \
       [[ -f /etc/systemd/system/getty@tty1.service.d/autologin.conf ]]; then
        log_success "autologin already configured"
        return 0
    fi

    # no dm, still ask user for autologin
    if [[ ${#found_dms[@]} -eq 0 ]]; then
        log_info "no display manager detected"
        if ask_yes_no "Enable TTY1 autologin?" "y"; then
            configure_tty1_autologin
            log_success "autologin configured"
        else
            log_info "skipped"
        fi
        return 0
    fi

    # build string
    local dm_display
    dm_display="$(printf '%s' "${found_dms[0]}")";
    local i
    for (( i=1; i<${#found_dms[@]}; i++ )); do
        dm_display+=", ${found_dms[$i]}"
    done

    # prompt
    echo ""
    echo "  ${YELLOW}${BOLD}Display manager detected:${RESET}  ${CYAN}${BOLD}${dm_display}${RESET}"
    echo ""
    printf "  disable & mask ${BOLD}%s${RESET} (takes effect on reboot, NOT stopped now)\n" "$dm_display"
    echo ""

    if ! ask_yes_no "Remove ${dm_display} and configure autologin?" "y"; then
        log_info "skipped"
        return 0
    fi

    # disable detected dm
    echo ""
    for dm in "${found_dms[@]}"; do
        disable_display_manager "$dm"
    done

    echo ""

    # config autologin
    configure_tty1_autologin

    log_success "done"
}

main "$@"
