# keyboard & language
input {
    kb_layout = us
    
    kb_options =
    
    resolve_binds_by_sym = false
    numlock_by_default = true
    
    repeat_rate = 35
    repeat_delay = 250
}

# mouse & pointer acceleration
input {
    follow_mouse = 1
    sensitivity = 0
    
    accel_profile = flat

    #raw input
    force_no_accel = false

    left_handed = false
    mouse_refocus = true
}

# scrolling
input {
    natural_scroll = false

    # for trackpad
    scroll_method = 2fg
    
}

# touchpad
input {
    touchpad {
        natural_scroll = true
        
        disable_while_typing = true

        tap-to-click = true

        clickfinger_behavior = false

        drag_lock = false
    }
}

# cursor 
cursor {
    sync_gsettings_theme = true

    no_hardware_cursors = 2

    use_cpu_buffer = 2
    
    # hide the cursor when typing
    hide_on_key_press = false

    # hide cursor after time (0=never)
    inactive_timeout = 0

    warp_on_change_workspace = 0
    no_break_fs_vrr = 2
    zoom_factor = 1.0
}

gestures {
    workspace_swipe_distance = 300
    workspace_swipe_cancel_ratio = 0.5
    workspace_swipe_invert = true
    workspace_swipe_create_new = true
    workspace_swipe_forever = false
}

# gesture var
$osdclient = swayosd-client

# 3-finger up swipe -> hyprexpo-toggle
gesture = 3, up, dispatcher, hyprexpo:expo, toggle 
# 3-finger left swipe -> swaync panal
gesture = 3, left, dispatcher, exec, swaync-client -t

# 3-finger down/right swipe -> mute/pause-play
gesture = 3, down, dispatcher, exec, $osdclient --output-volume mute-toggle
gesture = 3, right, dispatcher, exec, $osdclient --playerctl play-pause

# 4-finger horizontal swipe -> brightness change
gesture = 4, left, dispatcher, exec, $osdclient --brightness -10
gesture = 4, right, dispatcher, exec, $osdclient --brightness +10

# 4-finger vertical swipe -> volume change
gesture = 4, up, dispatcher, exec, $osdclient --output-volume +10 --max-volume 95
gesture = 4, down, dispatcher, exec, $osdclient --output-volume -10 --max-volume 95

# 3-finger pinch in -> Lock screen
gesture = 3, pinchout, dispatcher, exec, hyprlock --immediate
# 3-finger pinch out -> screenshot
gesture = 3, pinchin, dispatcher, exec, slurp | grim -g - - | swappy -f -
# 2-finger pinch out -> screenshot
gesture = 4, pinchout, dispatcher, exec, swaync-client -t

