# Hyprland main configuration

# monitors
source = ~/.config/hypr/source/monitors.conf

# programs & environment
source = ~/.config/hypr/source/environment_variables.conf

# plugins (if any)
source = ~/.config/hypr/source/plugins.conf

# input devices
source = ~/.config/hypr/source/input.conf

# appearance
source = ~/.config/hypr/source/appearance.conf

# window rules & workspaces
source = ~/.config/hypr/source/window_rules.conf

# keybindings
source = ~/.config/hypr/source/keybinds.conf

# autostart
source = ~/.config/hypr/source/autostart.conf

# power mode override
source = ~/.config/hypr/source/power-mode.conf

# personal stuffs you can remove:
device {
    name = wacom-hid-517d-finger
    enabled = false
}

device {
    name = wacom-hid-517d-pen
    enabled = false
}
