general {
    lock_cmd         = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd  = hyprctl dispatch dpms on
}

# dim screen
listener {
    timeout   = 300
    on-timeout = brightnessctl -s set 20%
    on-resume  = brightnessctl -r
}

# screen off
listener {
    timeout   = 360
    on-timeout = hyprctl dispatch dpms off
    on-resume  = hyprctl dispatch dpms on
}

# suspend
listener {
    timeout   = 600
    on-timeout = systemctl suspend
}

# poweroff after extended idle
listener {
    timeout   = 1500
    on-timeout = systemctl poweroff
}
