# ssh/rdp session config - format: name | protocol | target | auth | key_path | icon
# auth: key or password, if using password set key_path to -

VPS with ssh key      | ssh | user@1.1.1.1   | key      | ~/.ssh/id_rsa | debian
VPS with password  | ssh | user@1.1.1.1  | password | -             | debian
windows rdp | rdp | user@1.1.1.1 | password | -             | windows
